//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rland2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADDRESS
    {
        public ADDRESS()
        {
            this.CANDIDATEs = new HashSet<CANDIDATE>();
            this.COMPANies = new HashSet<COMPANY>();
            this.CONTRACTORs = new HashSet<CONTRACTOR>();
            this.EMPLOYEEs = new HashSet<EMPLOYEE>();
            this.SUBSCRIBERs = new HashSet<SUBSCRIBER>();
        }
    
        public int ID { get; set; }
        public string ADDR1 { get; set; }
        public string ADDR2 { get; set; }
        public string ADDR3 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string POSTAL_CD { get; set; }
        public string COUNTRY { get; set; }
        public string PHONE1 { get; set; }
        public string PHONE2 { get; set; }
        public string FAX { get; set; }
        public string IS_DELETED { get; set; }
        public string CR_BY { get; set; }
        public Nullable<System.DateTime> DT_CR { get; set; }
        public string MOD_BY { get; set; }
        public Nullable<System.DateTime> DT_MOD { get; set; }
    
        public virtual ICollection<CANDIDATE> CANDIDATEs { get; set; }
        public virtual ICollection<COMPANY> COMPANies { get; set; }
        public virtual ICollection<CONTRACTOR> CONTRACTORs { get; set; }
        public virtual ICollection<EMPLOYEE> EMPLOYEEs { get; set; }
        public virtual ICollection<SUBSCRIBER> SUBSCRIBERs { get; set; }
    }
}
