//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rland2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTIFACT
    {
        public int ID { get; set; }
        public int ARTIFACT_TYPE { get; set; }
        public int RES_ID { get; set; }
        public string RES_TYPE { get; set; }
        public string PATH { get; set; }
        public string NAME { get; set; }
        public byte[] CONTENT { get; set; }
        public string IS_DELETED { get; set; }
        public string CR_BY { get; set; }
        public Nullable<System.DateTime> DT_CR { get; set; }
        public string MOD_BY { get; set; }
        public Nullable<System.DateTime> DT_MOD { get; set; }
    
        public virtual ARTIFACT_TYPE_LKUP ARTIFACT_TYPE_LKUP { get; set; }
    }
}
