//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rland2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CANDIDATE_SOCIALMEDIA_SELECTED_URLS
    {
        public int ID { get; set; }
        public Nullable<int> CANDIDATE_ID { get; set; }
        public Nullable<int> SOCIALMEDIA_SELECTED { get; set; }
        public string SOCIALNETWORKING_URL { get; set; }
        public string IS_DELETED { get; set; }
        public Nullable<System.DateTime> DT_CR { get; set; }
        public string CR_BY { get; set; }
        public Nullable<System.DateTime> DT_MOD { get; set; }
        public string MOD_BY { get; set; }
    
        public virtual CANDIDATE CANDIDATE { get; set; }
        public virtual SOCIALMEDIA_LKUP SOCIALMEDIA_LKUP { get; set; }
    }
}
