//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rland2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANY
    {
        public COMPANY()
        {
            this.CANDIDATEs = new HashSet<CANDIDATE>();
            this.SIGNATUREs = new HashSet<SIGNATURE>();
            this.COMPANY_CLIENTS = new HashSet<COMPANY_CLIENTS>();
            this.CONTRACTORs = new HashSet<CONTRACTOR>();
            this.EMPLOYEEs = new HashSet<EMPLOYEE>();
            this.RESOURCE_PROFILE = new HashSet<RESOURCE_PROFILE>();
            this.SUBSCRIBERs = new HashSet<SUBSCRIBER>();
            this.SUBSCRIPTIONs = new HashSet<SUBSCRIPTION>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string DBA { get; set; }
        public string CATEGORY { get; set; }
        public string WEBSITE { get; set; }
        public int ADDR_ID { get; set; }
        public Nullable<int> NOTIFICATION_ID { get; set; }
        public string TAX_ID { get; set; }
        public string TECH_USED { get; set; }
        public string NOTES { get; set; }
        public string STAT { get; set; }
        public string IS_DELETED { get; set; }
        public string CR_BY { get; set; }
        public Nullable<System.DateTime> DT_CR { get; set; }
        public string MOD_BY { get; set; }
        public Nullable<System.DateTime> DT_MOD { get; set; }
    
        public virtual ADDRESS ADDRESS { get; set; }
        public virtual ICollection<CANDIDATE> CANDIDATEs { get; set; }
        public virtual ICollection<SIGNATURE> SIGNATUREs { get; set; }
        public virtual ICollection<COMPANY_CLIENTS> COMPANY_CLIENTS { get; set; }
        public virtual NOTIFICATION NOTIFICATION { get; set; }
        public virtual ICollection<CONTRACTOR> CONTRACTORs { get; set; }
        public virtual ICollection<EMPLOYEE> EMPLOYEEs { get; set; }
        public virtual ICollection<RESOURCE_PROFILE> RESOURCE_PROFILE { get; set; }
        public virtual ICollection<SUBSCRIBER> SUBSCRIBERs { get; set; }
        public virtual ICollection<SUBSCRIPTION> SUBSCRIPTIONs { get; set; }
    }
}
