//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rland2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRACTOR
    {
        public int ID { get; set; }
        public string TYPE { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string USER_ID { get; set; }
        public string SEX { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public int ADDR_ID { get; set; }
        public int COMP_ID { get; set; }
        public string EMPLR_NAME { get; set; }
        public string EMPLR_PHONE { get; set; }
        public string CONTACT_CONTRACTOR { get; set; }
        public int CLIENT_ID { get; set; }
        public Nullable<int> SKILL_ID { get; set; }
        public int NOTIFICATION_ID { get; set; }
        public Nullable<bool> PROSPECTIVE_EMP { get; set; }
        public string EMP_TYPE_NEEDED { get; set; }
        public string PYMT_PERIOD { get; set; }
        public string CURR_PAY { get; set; }
        public string DESIRED_PAY { get; set; }
        public Nullable<System.DateTime> DATE_AVAILABLE { get; set; }
        public string REF_BY { get; set; }
        public bool RELOCATE { get; set; }
        public string RELOC_PREFERENCES { get; set; }
        public Nullable<int> ETHINIC_TYPE { get; set; }
        public Nullable<int> RESIDENCY { get; set; }
        public string VETERAN { get; set; }
        public string DISABILITY { get; set; }
        public string STAT { get; set; }
        public string IS_DELETED { get; set; }
        public string CR_BY { get; set; }
        public Nullable<System.DateTime> DT_CR { get; set; }
        public string MOD_BY { get; set; }
        public Nullable<System.DateTime> DT_MOD { get; set; }
    
        public virtual ADDRESS ADDRESS { get; set; }
        public virtual CLIENT CLIENT { get; set; }
        public virtual COMPANY COMPANY { get; set; }
        public virtual CONTRACTOR CONTRACTOR1 { get; set; }
        public virtual CONTRACTOR CONTRACTOR2 { get; set; }
        public virtual NOTIFICATION NOTIFICATION { get; set; }
        public virtual SKILL SKILL { get; set; }
    }
}
