//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rland2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOURS_LOGGED
    {
        public int ID { get; set; }
        public int TIMESHEET_ID { get; set; }
        public int PROJ_ID { get; set; }
        public string DESCR { get; set; }
        public int SUN_HRS { get; set; }
        public int MON_HRS { get; set; }
        public int TUE_HRS { get; set; }
        public int WED_HRS { get; set; }
        public int THU_HRS { get; set; }
        public int FRI_HRS { get; set; }
        public int SAT_HRS { get; set; }
        public bool WORKED_ON_HOLIDAY { get; set; }
        public string IS_DELETED { get; set; }
        public string CR_BY { get; set; }
        public Nullable<System.DateTime> DT_CR { get; set; }
        public string MOD_BY { get; set; }
        public Nullable<System.DateTime> DT_MOD { get; set; }
    
        public virtual PROJECT PROJECT { get; set; }
        public virtual TIMESHEET TIMESHEET { get; set; }
    }
}
