//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rland2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSTING_SUBMISSION
    {
        public POSTING_SUBMISSION()
        {
            this.SUBMISSION_STATUS = new HashSet<SUBMISSION_STATUS>();
        }
    
        public int ID { get; set; }
        public int POSTING_ID { get; set; }
        public string POSTING_TYPE { get; set; }
        public string RES_TYPE { get; set; }
        public int RES_ID { get; set; }
        public Nullable<System.DateTime> DT_CR { get; set; }
        public string CR_BY { get; set; }
        public Nullable<System.DateTime> DT_MOD { get; set; }
        public string MOD_BY { get; set; }
        public string IS_DELETED { get; set; }
        public Nullable<System.DateTime> START_DT { get; set; }
        public Nullable<System.DateTime> END_DT { get; set; }
    
        public virtual ICollection<SUBMISSION_STATUS> SUBMISSION_STATUS { get; set; }
    }
}
