//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rland2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECT
    {
        public PROJECT()
        {
            this.HOURS_LOGGED = new HashSet<HOURS_LOGGED>();
            this.PROJECT_RESOURCE = new HashSet<PROJECT_RESOURCE>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string DESCR { get; set; }
        public string MANAGER { get; set; }
        public string MGR_PHONE { get; set; }
        public Nullable<System.DateTime> START_DT { get; set; }
        public Nullable<System.DateTime> END_DT { get; set; }
        public Nullable<decimal> BUDGET { get; set; }
        public string TECH_USED { get; set; }
        public bool CLIENT_PROJECT { get; set; }
        public int SPONSOR_ID { get; set; }
        public string NOTES { get; set; }
        public string STAT { get; set; }
        public string IS_DELETED { get; set; }
        public string CR_BY { get; set; }
        public Nullable<System.DateTime> DT_CR { get; set; }
        public string MOD_BY { get; set; }
        public Nullable<System.DateTime> DT_MOD { get; set; }
        public Nullable<int> COMP_ID { get; set; }
    
        public virtual ICollection<HOURS_LOGGED> HOURS_LOGGED { get; set; }
        public virtual ICollection<PROJECT_RESOURCE> PROJECT_RESOURCE { get; set; }
    }
}
