//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rland2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESOURCE_PROFILE
    {
        public int ID { get; set; }
        public int COMP_ID { get; set; }
        public int RES_ID { get; set; }
        public string RES_TYPE { get; set; }
        public string EMPLOYMENT_TYPE { get; set; }
        public string DESIGNATION { get; set; }
        public string EXPERIENCE { get; set; }
        public string WORK_COMPANY_NAME { get; set; }
        public string WORK_LOCATION { get; set; }
        public System.DateTime START_DT { get; set; }
        public Nullable<System.DateTime> END_DT { get; set; }
        public string IS_DELETED { get; set; }
        public string CR_BY { get; set; }
        public Nullable<System.DateTime> DT_CR { get; set; }
        public string MOD_BY { get; set; }
        public Nullable<System.DateTime> DT_MOD { get; set; }
    
        public virtual COMPANY COMPANY { get; set; }
        public virtual RESOURCE_PROFILE RESOURCE_PROFILE1 { get; set; }
        public virtual RESOURCE_PROFILE RESOURCE_PROFILE2 { get; set; }
    }
}
