//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rland2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RL_USERS
    {
        public RL_USERS()
        {
            this.SIGNATUREs = new HashSet<SIGNATURE>();
        }
    
        public int ID { get; set; }
        public string RES_TYPE { get; set; }
        public string USER_ID { get; set; }
        public string PWD { get; set; }
        public string NAME { get; set; }
        public string DESCR { get; set; }
        public Nullable<int> NOTIFICATION_ID { get; set; }
        public Nullable<int> COMP_ID { get; set; }
        public string USER_ACTIVATED { get; set; }
        public bool ACCT_LOCKED { get; set; }
        public Nullable<int> QNO_1 { get; set; }
        public string ANS_1 { get; set; }
        public string HNT_1 { get; set; }
        public Nullable<int> QNO_2 { get; set; }
        public string ANS_2 { get; set; }
        public string HNT_2 { get; set; }
        public Nullable<int> QNO_3 { get; set; }
        public string ANS_3 { get; set; }
        public string HNT_3 { get; set; }
        public string STAT { get; set; }
        public string IS_DELETED { get; set; }
        public string CR_BY { get; set; }
        public Nullable<System.DateTime> DT_CR { get; set; }
        public string MOD_BY { get; set; }
        public Nullable<System.DateTime> DT_MOD { get; set; }
    
        public virtual ICollection<SIGNATURE> SIGNATUREs { get; set; }
    }
}
