//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rland2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHEDULER_EXECUTION_LOG
    {
        public int ID { get; set; }
        public string COMMUNICATION_MODE { get; set; }
        public string CONTACT_ID { get; set; }
        public int COMP_ID { get; set; }
        public int RES_ID { get; set; }
        public string RES_TYPE { get; set; }
        public int SCHEDULER_ID { get; set; }
        public Nullable<System.DateTime> EXECUTION_START_TIME { get; set; }
        public Nullable<System.DateTime> EXECUTION_END_TIME { get; set; }
        public string STAT { get; set; }
        public string STAT_MSG { get; set; }
        public string IS_DELETED { get; set; }
        public string CR_BY { get; set; }
        public Nullable<System.DateTime> DT_CR { get; set; }
        public string MOD_BY { get; set; }
        public Nullable<System.DateTime> DT_MOD { get; set; }
    }
}
