//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rland2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCREEN_ACTION
    {
        public SCREEN_ACTION()
        {
            this.FEATURE_ACCESS = new HashSet<FEATURE_ACCESS>();
        }
    
        public int ID { get; set; }
        public string SCREEN_NAME { get; set; }
        public string ACTION { get; set; }
        public string IS_DELETED { get; set; }
        public string CR_BY { get; set; }
        public Nullable<System.DateTime> DT_CR { get; set; }
        public string MOD_BY { get; set; }
        public Nullable<System.DateTime> DT_MOD { get; set; }
    
        public virtual ICollection<FEATURE_ACCESS> FEATURE_ACCESS { get; set; }
    }
}
