//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rland2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SETTING
    {
        public int ID { get; set; }
        public int SESSION_TIMEOUT_IN_MINS { get; set; }
        public string SMTP_CLIENT { get; set; }
        public int SMTP_PORT { get; set; }
        public bool ENABLE_SSL { get; set; }
        public bool USE_DEFAULT_CREDENTIALS { get; set; }
        public Nullable<int> ADDR1_ID { get; set; }
        public Nullable<int> ADDR2_ID { get; set; }
        public string PUBLIC_MSG { get; set; }
        public Nullable<System.DateTime> MSG_EFF_FROM { get; set; }
        public Nullable<System.DateTime> MSG_EFF_TO { get; set; }
        public string STAT { get; set; }
        public string CR_BY { get; set; }
        public Nullable<System.DateTime> DT_CR { get; set; }
        public string MOD_BY { get; set; }
        public Nullable<System.DateTime> DT_MOD { get; set; }
    }
}
