//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rland2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIGNATURE
    {
        public int ID { get; set; }
        public Nullable<int> COMP_ID { get; set; }
        public Nullable<int> RES_ID { get; set; }
        public string RES_TYPE { get; set; }
        public string SIGNATURE_CONTENT { get; set; }
        public string SIGNATURE_TYPE { get; set; }
        public Nullable<bool> IS_DEFAULT { get; set; }
        public string IS_DELETED { get; set; }
        public string CR_BY { get; set; }
        public Nullable<System.DateTime> DT_CR { get; set; }
        public string MOD_BY { get; set; }
        public Nullable<System.DateTime> DT_MOD { get; set; }
    
        public virtual COMPANY COMPANY { get; set; }
        public virtual RL_USERS RL_USERS { get; set; }
    }
}
