//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rland2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SKILL
    {
        public SKILL()
        {
            this.CANDIDATEs = new HashSet<CANDIDATE>();
            this.CONTRACTORs = new HashSet<CONTRACTOR>();
            this.EMPLOYEEs = new HashSet<EMPLOYEE>();
            this.JOBs = new HashSet<JOB>();
        }
    
        public int ID { get; set; }
        public string TECH_SKILLS { get; set; }
        public string SOFT_SKILLS { get; set; }
        public string IS_DELETED { get; set; }
        public string CR_BY { get; set; }
        public Nullable<System.DateTime> DT_CR { get; set; }
        public string MOD_BY { get; set; }
        public Nullable<System.DateTime> DT_MOD { get; set; }
    
        public virtual ICollection<CANDIDATE> CANDIDATEs { get; set; }
        public virtual ICollection<CONTRACTOR> CONTRACTORs { get; set; }
        public virtual ICollection<EMPLOYEE> EMPLOYEEs { get; set; }
        public virtual ICollection<JOB> JOBs { get; set; }
    }
}
