//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rland2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMTP_CLIENT
    {
        public int ID { get; set; }
        public string MSG_TYPE { get; set; }
        public string SMTP_CLIENT1 { get; set; }
        public int SMTP_PORT { get; set; }
        public bool ENABLE_SSL { get; set; }
        public Nullable<bool> REQ_AUTHENTICATION { get; set; }
        public string USER_ID { get; set; }
        public string PWD { get; set; }
        public string IS_DELETED { get; set; }
        public string CR_BY { get; set; }
        public Nullable<System.DateTime> DT_CR { get; set; }
        public string MOD_BY { get; set; }
        public Nullable<System.DateTime> DT_MOD { get; set; }
    }
}
