//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rland2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOCIALMEDIA_LKUP
    {
        public SOCIALMEDIA_LKUP()
        {
            this.CANDIDATE_SOCIALMEDIA_SELECTED_URLS = new HashSet<CANDIDATE_SOCIALMEDIA_SELECTED_URLS>();
        }
    
        public int ID { get; set; }
        public string SOCIALMEDIA_NAME { get; set; }
        public string SOCIALMEDIA_URL { get; set; }
        public Nullable<System.DateTime> DT_CR { get; set; }
        public string CR_BY { get; set; }
        public Nullable<System.DateTime> DT_MOD { get; set; }
        public string MOD_BY { get; set; }
        public string IS_DELETED { get; set; }
    
        public virtual ICollection<CANDIDATE_SOCIALMEDIA_SELECTED_URLS> CANDIDATE_SOCIALMEDIA_SELECTED_URLS { get; set; }
    }
}
