//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rland2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBSCRIPTION_PACKAGE
    {
        public SUBSCRIPTION_PACKAGE()
        {
            this.INVOICEs = new HashSet<INVOICE>();
            this.SUBSCRIPTIONs = new HashSet<SUBSCRIPTION>();
        }
    
        public int ID { get; set; }
        public int SPKG_PERIOD_ID { get; set; }
        public string NAME { get; set; }
        public string PERIOD { get; set; }
        public decimal USD_COST { get; set; }
        public decimal EUR_COST { get; set; }
        public decimal UK_COST { get; set; }
        public decimal INR_COST { get; set; }
        public string IS_DELETED { get; set; }
        public string CR_BY { get; set; }
        public Nullable<System.DateTime> DT_CR { get; set; }
        public string MOD_BY { get; set; }
        public Nullable<System.DateTime> DT_MOD { get; set; }
    
        public virtual ICollection<INVOICE> INVOICEs { get; set; }
        public virtual ICollection<SUBSCRIPTION> SUBSCRIPTIONs { get; set; }
        public virtual SUBSCRIPTION_PACKAGE_PERIOD SUBSCRIPTION_PACKAGE_PERIOD { get; set; }
    }
}
