//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rland2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBSCRIBER
    {
        public int ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string USER_ID { get; set; }
        public Nullable<int> ADDR_ID { get; set; }
        public int COMP_ID { get; set; }
        public int NOTIFICATION_ID { get; set; }
        public string EMAIL_ID { get; set; }
        public string ROLE { get; set; }
        public string STAT { get; set; }
        public string IS_DELETED { get; set; }
        public string CR_BY { get; set; }
        public Nullable<System.DateTime> DT_CR { get; set; }
        public string MOD_BY { get; set; }
        public Nullable<System.DateTime> DT_MOD { get; set; }
    
        public virtual ADDRESS ADDRESS { get; set; }
        public virtual COMPANY COMPANY { get; set; }
        public virtual NOTIFICATION NOTIFICATION { get; set; }
    }
}
