//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rland2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBSCRIPTION_PACKAGE_PERIOD
    {
        public SUBSCRIPTION_PACKAGE_PERIOD()
        {
            this.SUBSCRIPTION_PACKAGE = new HashSet<SUBSCRIPTION_PACKAGE>();
        }
    
        public int ID { get; set; }
        public System.DateTime EFF_FROM { get; set; }
        public System.DateTime EFF_TO { get; set; }
        public bool TRIAL { get; set; }
        public int PKG_CNT { get; set; }
        public string DESCR { get; set; }
        public string IS_DELETED { get; set; }
        public string CR_BY { get; set; }
        public Nullable<System.DateTime> DT_CR { get; set; }
        public string MOD_BY { get; set; }
        public Nullable<System.DateTime> DT_MOD { get; set; }
    
        public virtual ICollection<SUBSCRIPTION_PACKAGE> SUBSCRIPTION_PACKAGE { get; set; }
    }
}
