//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rland2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIMESHEET
    {
        public TIMESHEET()
        {
            this.HOURS_LOGGED = new HashSet<HOURS_LOGGED>();
            this.TIMESHEET_LOG = new HashSet<TIMESHEET_LOG>();
        }
    
        public int ID { get; set; }
        public int WEEK_CAL_ID { get; set; }
        public int COMP_ID { get; set; }
        public int RES_ID { get; set; }
        public string RES_TYPE { get; set; }
        public string IS_DELETED { get; set; }
        public string CR_BY { get; set; }
        public Nullable<System.DateTime> DT_CR { get; set; }
        public string MOD_BY { get; set; }
        public Nullable<System.DateTime> DT_MOD { get; set; }
    
        public virtual ICollection<HOURS_LOGGED> HOURS_LOGGED { get; set; }
        public virtual ICollection<TIMESHEET_LOG> TIMESHEET_LOG { get; set; }
    }
}
